#!/usr/bin/env python

import sys, os, re

# stopwords
stopwords = ['and', 'but', 'is', 'the', 'to']

for line in sys.stdin:
	# remove leading and trailing whitespace
	line = line.strip()
	# remove numbers
	text = re.sub(pattern=r"\d", repl=r"", string=line)
	# only contains lowercase words
	words = re.findall(r'\w+', text.lower())

	# Get the file path
	doc_path = os.environ["map_input_file"]
	 
	# Get the filename from the file path
	doc_id = os.path.split(doc_path)[-1]

	# Mapper output
	for word in words:
		# don't include stopwords
		if word not in stopwords:
			# separated by :, and write results to STDOUT
			print ('%s:%s' % (word, doc_id))

